import React, { useState } from "react";
import mascot from "@/imports/mascot.png";
import { getStoredTeachers } from "@/store";
import { Teacher } from "@/types";
import { ArrowLeft, LogIn } from "lucide-react";

interface Props { onSuccess: (teacher: Teacher) => void; onNavigateRegister: () => void; onBack: () => void; }
export default function TeacherLogin({ onSuccess, onNavigateRegister, onBack }: Props) {
  const [email, setEmail] = useState("ana@escola.com"); const [password, setPassword] = useState("123"); const [error, setError] = useState("");
  const handleLogin = (e?: React.FormEvent) => { e?.preventDefault(); setError(""); const found = getStoredTeachers().find((t) => t.email.trim().toLowerCase() === email.trim().toLowerCase() && t.password === password); if (found) onSuccess(found); else setError("Email ou senha incorretos. Tente ana@escola.com com senha 123."); };
  return <main className="min-h-screen bg-[#f8fafc] px-5 py-8 sm:px-10"><div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-5xl items-center"><div className="w-full max-w-md"><button onClick={onBack} className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft className="h-4 w-4" /> Voltar ao início</button><div className="soft-panel p-7 sm:p-9"><div className="mb-8 flex items-center gap-3"><img src={mascot} alt="Mascote" className="h-12 w-12 object-contain" /><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-rose-500">Letter Play</p><h1 className="font-title text-3xl font-bold text-slate-950">Área do professor</h1></div></div><p className="mb-7 text-sm leading-relaxed text-slate-500">Gerencie suas turmas e acompanhe a evolução da turma.</p>{error && <div className="mb-4 border-l-2 border-rose-500 bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700">{error}</div>}<form onSubmit={handleLogin} className="space-y-5"><label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">Email institucional</span><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="w-full border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-rose-500" /></label><label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-500">Senha</span><input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} className="w-full border border-slate-300 bg-white px-4 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-rose-500" /></label><button type="submit" className="flex w-full items-center justify-center gap-2 bg-rose-500 px-4 py-3.5 text-sm font-extrabold text-white hover:bg-rose-600"><LogIn className="h-4 w-4" /> Acessar painel</button></form><div className="mt-6 flex flex-col gap-2 border-t border-slate-100 pt-4"><button onClick={onNavigateRegister} className="text-left text-sm font-bold text-slate-700 hover:text-rose-600">Criar uma conta de professor →</button><span className="text-xs text-slate-400">Demonstração: ana@escola.com / 123</span></div></div></div></div></main>;
}
